[package]
name = "feryr_external"
version = "0.1.0"
edition = "2021"    
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
autotools = "0.2"
cc = "1.0"
cmake = "0.1"
failure = "0.1"
lazy_static = "1"
