name: CI(Linux)
on: 
  pull_request:
    types:[opened, synchronize, reopened]
  push:
    branches:
      - master
      - binary-instrument
      - origin/binary-instrument
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install clippy
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Generate Cargo.lock
        uses: actions-rs/cargo@v1
        with:
          command: generate-lockfile
      
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v1.0.1
        
      - name: check build
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all --bins --examples --tests

      - name: Clear the cargo caches
        run: |
          cargo install cargo-cache --no-default-features --features ci-autoclean
          cargo-cache
